/**
 * Simple Hello World API
 * API for Hello World Service.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
export interface ExchangeRates {
    aUD?: string;
    bGN?: string;
    bRL?: string;
    cAD?: string;
    cHF?: string;
    cNY?: string;
    cZK?: string;
    dKK?: string;
    gBP?: string;
    hKD?: string;
    hRK?: string;
    hUF?: string;
    iDR?: string;
    iLS?: string;
    iNR?: string;
    iSK?: string;
    jPY?: string;
    kRW?: string;
    mXN?: string;
    mYR?: string;
    nOK?: string;
    nZD?: string;
    pHP?: string;
    pLN?: string;
    rON?: string;
    rUB?: string;
    sEK?: string;
    sGD?: string;
    tHB?: string;
    tRY?: string;
    uSD?: string;
    zAR?: string;
}
