swagger: '2.0'
info:
  title: Simple Hello World API
  description: API for Hello World Service.
  version: '1.0'
produces:
  - application/json
consumes:
  - application/json
  - application/octet-stream
host: 'localhost:8001'
basePath: /api
paths:
  /hello:
    post:
      x-swagger-router-controller: helloWorldRoute
      operationId: helloWorldPost
      tags:
        - /hello
      description: Returns Hello world string via POST.
      parameters:
        - name: greeting
          in: body
          description: Name of greeting
          required: true
          schema:
            $ref: '#/definitions/Greeting'
      responses:
        '200':
          description: Successful request.
          schema:
            $ref: '#/definitions/Hello'
        default:
          description: Invalid request.
          schema:
            $ref: '#/definitions/Error'
    get:
      x-swagger-router-controller: helloWorldRoute
      operationId: helloWorldGet
      tags:
        - /hello
      description: Returns Hello world string via GET.
      parameters:
        - name: name
          in: query
          description: Name
          required: true
          type: string
        - name: surname
          in: query
          description: Surname
          required: true
          type: string
      responses:
        '200':
          description: Successful request.
          schema:
            $ref: '#/definitions/Hello'
        default:
          description: Invalid request.
          schema:
            $ref: '#/definitions/Error'
definitions:
  Hello:
    properties:
      msg:
        type: string
    required:
      - msg
  Greeting:
    properties:
      name:
        type: string
      surname:
        type: string
    required:
      - name
      - surname
  Exchange:
    type: object
    required:
      - base
      - date
      - rates
    properties:
      base:
        type: string
      date:
        type: string
      rates:
        type: object
        properties:
          AUD:
            type: string
          BGN:
            type: string
          BRL:
            type: string
          CAD:
            type: string
          CHF:
            type: string
          CNY:
            type: string
          CZK:
            type: string
          DKK:
            type: string
          GBP:
            type: string
          HKD:
            type: string
          HRK:
            type: string
          HUF:
            type: string
          IDR:
            type: string
          ILS:
            type: string
          INR:
            type: string
          ISK:
            type: string
          JPY:
            type: string
          KRW:
            type: string
          MXN:
            type: string
          MYR:
            type: string
          NOK:
            type: string
          NZD:
            type: string
          PHP:
            type: string
          PLN:
            type: string
          RON:
            type: string
          RUB:
            type: string
          SEK:
            type: string
          SGD:
            type: string
          THB:
            type: string
          TRY:
            type: string
          USD:
            type: string
          ZAR:
            type: string
  Error:
    type: object
    required:
      - message
    properties:
      message:
        type: string
      extra:
        type: object
      code:
        type: string

