swagger: '2.0'
info:
  title: Simple Hello World API
  description: API for Hello World Service.
  version: '1.0'
produces:
  - application/json
consumes:
  - application/json
  - application/octet-stream
host: 'localhost:8001'
basePath: /api
paths:
  /exchange/latest:
    get:
      x-swagger-router-controller: exchangeRoute
      operationId: exchangeGet
      tags:
        - Exchange
      description: Get the latest exchange rates based on currency
      parameters:
        - name: base
          in: query
          description: Base currency name
          required: true
          type: string
      responses:
        '200':
          description: successful response
          schema:
            $ref: '#/definitions/Exchange'
        default:
          description: Invalid request.
          schema:
            $ref: '#/definitions/Error'
definitions:
  Exchange:
    type: object
    required:
      - base
      - date
      - rates
    properties:
      base:
        type: string
      date:
        type: string
      rates:
        type: object
        properties:
          AUD:
            type: string
          BGN:
            type: string
          BRL:
            type: string
          CAD:
            type: string
          CHF:
            type: string
          CNY:
            type: string
          CZK:
            type: string
          DKK:
            type: string
          GBP:
            type: string
          HKD:
            type: string
          HRK:
            type: string
          HUF:
            type: string
          IDR:
            type: string
          ILS:
            type: string
          INR:
            type: string
          ISK:
            type: string
          JPY:
            type: string
          KRW:
            type: string
          MXN:
            type: string
          MYR:
            type: string
          NOK:
            type: string
          NZD:
            type: string
          PHP:
            type: string
          PLN:
            type: string
          RON:
            type: string
          RUB:
            type: string
          SEK:
            type: string
          SGD:
            type: string
          THB:
            type: string
          TRY:
            type: string
          USD:
            type: string
          ZAR:
            type: string
  Error:
    type: object
    required:
      - message
    properties:
      message:
        type: string
      extra:
        type: object
      code:
        type: string

